### PR TITLE
FSE API Hits Counter

### PR DESCRIPTION
**Pull request by jsilva74**
### Use case
I, as an user, wanna to know how many requests was sent to FSE API in past 6 hours to stick with FSE User Guide related to the use of API.

### Proposed solution
This PR implements a counter to accumulate the total quantity of requests sent to FSE API. Also, displays this information in Update screen with 3 levels of severities.
Captura de Tela 2023-11-30 às 05 21 28
_Total of requests to FSE API up to 24 requests in past 6 hours_

Captura de Tela 2023-11-30 às 05 30 17
_Total of requests to FSE API from 25 to 34 requests in past 6 hours_

Captura de Tela 2023-11-30 às 05 30 52
_Total of requests to FSE API with more than 34 requests in past 6 hours_

### CODE REVIEW

**Comment by piero-la-lune** [comment]
Hi @jsilva74 

Thank you very much for your contribution!

If I may, I would suggest that you update the hit counter when opening the "Load data" popup, because I can see a use case when a user has done 6 requests, then comes back to FSE Planner the next day and sees "6 requests in the last 6 hours" when opening the popup, it would be a bit confusing.

**Comment by jsilva74** [comment]
Hey Piero.

Sure. I'll fix it. Thanks for the insight.

**Comment by jsilva74** [comment]
@piero-la-lune, branch updated. Thanks.

**Comment by piero-la-lune** [comment]
Looks ok, thanks!

**Pull request merged**
